### ISSUE TITLE
A simple post request.

### ISSUE THREAD

**Issue by Anatoli113** [botletics/SIM7500-LTE-Shield#1]
Hi,

I am going to use the following module.
https://www.aliexpress.com/item/4G-Breakout-board-in-American-with-SIM7500A-on-board-SIM7500A-breakout-board-1PC-free-shipping-no/32851163595.html
The SIM card I am using is IoT sim card from Aeris. https://www.aeris.com/

I am going to write a code to send the simple post request.
I want to know if I can use your Adafruit Fona library directly without any change.

And I want to know which example of your codes I should use for my simple POST request code.
I am a beginner, so I hope you will let you know the way for it.

One more thing! The BK-SIM7500 breakout board has SLEEP pins instead of reset pin.
I don't know how to consider the sleep signal in my code.

Thanks in advance!

**Comment by botletics** [comment]
Hi,

The [IoT_Example sketch](https://github.com/botletics/SIM7000-LTE-Shield/tree/master/Code/examples/IoT_Example) supports HTTP and HTTPS functions for the SIM7500. However, I cannot guarantee anything or offer technical support for hardware other than mine.
