### ISSUE TITLE
Schematics and Linux driver

### ISSUE THREAD

**Issue by gamelaster** [botletics/SIM7500-LTE-Shield#2]
Hello,

Do you plan to release at least schematics and Linux driver for SIM7500? I know there is already things for SIM7000, but I need also voice support. It would be really nice to have this.

Thank you

**Comment by botletics** [comment]
Not at this moment. I'm still finalizing things and want to get some more exposure first before releasing design files. I don't have Linux drivers (they would be from SIMCom and they didn't give them to me).

**Comment by gamelaster** [comment]
Oh nice! Thank you for information
