### ISSUE TITLE
[Firmware Updater]

### ISSUE THREAD

**Issue by mamuncloud** [botletics/SIM7500-LTE-Shield#3]
why the updater is empty, where I can find that ??

**Comment by gamelaster** [comment]
Try updater from SIM7000, it should work

**Comment by botletics** [comment]
Im not sure what you mean by "empty". The firmware update tool is [this file](https://github.com/botletics/SIM7000-LTE-Shield/blob/master/SIM7000%20Documentation/Firmware%20Updater%20Tool/SIM7000%20QDL%20V1.34%20Only%20for%20Update.zip)
