### ISSUE TITLE
Update Firmware SIM7600

### ISSUE THREAD

**Issue by mamuncloud** [botletics/SIM7500-LTE-Shield#4]
hello, can I ask the new firmware file for sim7600, i have not found until now..
thanks, mr. timothy

**Comment by botletics** [comment]
Sorry I don't have it.

**Comment by mamuncloud** [comment]
oke I found [it](https://www.waveshare.com/wiki/SIM7600E-H_4G_HAT) but in my country must use a web proxy to get it...
thanks

**Comment by Alisson1998** [comment]
OLA TEM COMO VC DEIXAR AQUI O FIRMWARE , PRECISO DELE !!
