### ISSUE TITLE
PCB files are missing

### ISSUE THREAD

**Issue by LeFEAR** [botletics/SIM7500-LTE-Shield#5]
PCb files are missing 
I would like to see how you implement RF tuning from the Chip to the SMS connector , 
quite new to this 
also is there a mode on the ship to show how well the VSWR or signal reception is ?

Thank you

**Comment by botletics** [comment]
They're on GitHub: https://github.com/botletics/SIM7000-LTE-Shield/tree/master/PCB%20Files

I didn't include pi filtering but might have empty pads for that in the future.

You can get network RSSI.
